name: Android CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Android App
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Ensure gradlew is executable
      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install dependencies
      - name: Install Dependencies
        run: ./gradlew dependencies

      # Lint the code
      - name: Run Lint
        run: ./gradlew lint

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
